import React, { useEffect, useState, Fragment } from "react";
import Papa from "papaparse";
import "../About/style.css";
// import firebase from '../../firebase';

// import { Container, Row, Col } from "react-bootstrap";
// import Particle from "../Particle";
// import Github from "./Github";
// import Techstack from "./Techstack";
// import Aboutcard from "./AboutCard";
// import laptopImg from "../../Assets/about.png";
// import Toolstack from "./Toolstack";
// import Table from "react-bootstrap/Table";
// import BootstrapTable from "react-bootstrap-table-next";
// import "react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.css";
// import paginationFactory from "react-bootstrap-table2-paginator";
// function About() {
//  const [data, setData] = useState({});
//  Papa.parse(
//    "https://docs.google.com/spreadsheets/d/e/2PACX-1vQSqcTXwKmnJMuG1742iERdwuMD8Ri-Bz8okCjZbM9tKU7w3PJWYZmofpZ-pP8HgmWsw-NM4q84xWSF/pub?gid=2004499149&single=true&output=csv",
//    {
//      download: true,
//      header: true,
//      complete: (results) => {
//        setData(results.data);
//      },
//    }
//  );

//  const movies = Array.from(data);
//   return (
//     <Container fluid className="about-section">
//       <Particle />
//       <Container>
//         <Row style={{ justifyContent: "center", padding: "10px" }}>
//           <Col
//             md={7}
//             style={{
//               justifyContent: "center",
//               paddingTop: "30px",
//               paddingBottom: "50px",
//             }}
//           >
//             <h1 style={{ fontSize: "2.1em", paddingBottom: "20px" }}>
//               Substation <strong className="purple">1</strong>
//             </h1>
//           </Col>
//         </Row>

//         <Table striped bordered hover variant="dark">

//           <thead>
//             <tr>
//               <th>Time</th>
//               <th>Humidity</th>
//               <th>Temperature</th>

//             </tr>
//           </thead>
//           <tbody>
//           {movies.map((data) => (
//             <tr key={data.Substation}>
//               <td>{data.Time}</td>
//               <td>{data.Humidity}</td>
//               <td>{data.Temperature}</td>
//             </tr>

//           ))}

//           </tbody>
//         </Table>

//       </Container>
//     </Container>
//   );
// }

// export default About;

import { MDBDataTable, MDBNavLink } from "mdbreact";

const About1 = () => {
  // const [data, setData] = useState([]);

  // useEffect(() => {
  //   const fetchGoogleSheetData = async () => {
  //     const csvUrl =
  //       "https://docs.google.com/spreadsheets/d/e/2PACX-1vQSqcTXwKmnJMuG1742iERdwuMD8Ri-Bz8okCjZbM9tKU7w3PJWYZmofpZ-pP8HgmWsw-NM4q84xWSF/pub?gid=0&single=true&output=csv"; // Replace with your Google Sheets CSV file URL
  //     const response = await fetch(csvUrl);
  //     const text = await response.text();
  //     const parsedData = Papa.parse(text, { header: true });
  //     setData(parsedData.data);

  //   };

  //   fetchGoogleSheetData();

  // }, []);

  const data = {
    columns: [
      {
        label: "SL",
        field: "SL",
        sort: "asc",
        width: 150,
      },
      {
        label: "Time",
        field: "Time",
        sort: "asc",
        width: 350,
      },
      {
        label: "Hydrogen",
        field: "Hydrogen",
        sort: "asc",
        width: 150,
      },
      {
        label: "Oxygen",
        field: "Oxygen",
        sort: "asc",
        width: 100,
      },
      {
        label: "Methane",
        field: "Methane",
        sort: "asc",
        width: 100,
      },
      {
        label: "CO",
        field: "CO",
        sort: "asc",
        width: 100,
      },
      {
        label: "CO2",
        field: "CO2",
        sort: "asc",
        width: 100,
      },
      {
        label: "Ethylene",
        field: "Ethylene",
        sort: "asc",
        width: 100,
      },
      {
        label: "Ethane",
        field: "Ethane",
        sort: "asc",
        width: 100,
      },
      {
        label: "Acethylene",
        field: "Acethylene",
        sort: "asc",
        width: 150,
      },
      {
        label: "DBDS",
        field: "DBDS",
        sort: "asc",
        width: 100,
      },
      {
        label: "PF",
        field: "Power_Factor",
        sort: "asc",
        width: 100,
      },
      {
        label: "IV",
        field: "Interfacial_V",
        sort: "asc",
        width: 100,
      },
      {
        label: "DR",
        field: "Dielectric_rigidity",
        sort: "asc",
        width: 100,
      },
      {
        label: "Humid",
        field: "Water_content",
        sort: "asc",
        width: 100,
      },
      {
        label: "HI",
        field: "Health_index",
        sort: "asc",
        width: 100,
      },
      // {
      //   label: "LE",
      //   field: "Life_expectation",
      //   sort: "asc",
      //   width: 100,
      // },
    ],
    rows: [
     
      {
        SL: "10",
        Time: "12:45 AM",
        Hydrogen: "488",
        Oxygen: "11861",
        Nitrogen: "48353",
        Methane: "13",
        CO: "85",
        CO2: "1957",
        Ethylene: "29",
        Ethane: "23",
        Acethylene: "0",
        DBDS: "164",
        Power_Factor: "0.27",
        Interfacial_V: "37",
        Dielectric_rigidity: "72",
        Water_content: "10",
        Health_index: "68",
      },
      {
        SL: "11",
        Time: "12:50 AM",
        Hydrogen: "4",
        Oxygen: "26100",
        Nitrogen: "60600",
        Methane: "1",
        CO: "206",
        CO2: "1440",
        Ethylene: "13",
        Ethane: "0",
        Acethylene: "13",
        DBDS: "5",
        Power_Factor: "1.32",
        Interfacial_V: "40",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "63.4",
      },
      {
        SL: "12",
        Time: "12:55 AM",
        Hydrogen: "4",
        Oxygen: "21800",
        Nitrogen: "46200",
        Methane: "0",
        CO: "75",
        CO2: "655",
        Ethylene: "3",
        Ethane: "0",
        Acethylene: "11",
        DBDS: "0",
        Power_Factor: "0.65",
        Interfacial_V: "42",
        Dielectric_rigidity: "53",
        Water_content: "5",
        Health_index: "63.4",
      },
      {
        SL: "13",
        Time: "1:00 AM",
        Hydrogen: "254",
        Oxygen: "592",
        Nitrogen: "60300",
        Methane: "14",
        CO: "376",
        CO2: "2500",
        Ethylene: "5",
        Ethane: "9",
        Acethylene: "0",
        DBDS: "205",
        Power_Factor: "0.44",
        Interfacial_V: "42",
        Dielectric_rigidity: "42",
        Water_content: "6",
        Health_index: "61.3",
      },
      {
        SL: "14",
        Time: "1:05 AM",
        Hydrogen: "23349",
        Oxygen: "2475",
        Nitrogen: "28011",
        Methane: "5045",
        CO: "156",
        CO2: "48",
        Ethylene: "5588",
        Ethane: "3532",
        Acethylene: "2951",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "52",
        Dielectric_rigidity: "70",
        Water_content: "2",
        Health_index: "60.5",
      },
      {
        SL: "15",
        Time: "1:10 AM",
        Hydrogen: "9040",
        Oxygen: "1870",
        Nitrogen: "47500",
        Methane: "1790",
        CO: "183",
        CO2: "2060",
        Ethylene: "7820",
        Ethane: "638",
        Acethylene: "1450",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "42",
        Dielectric_rigidity: "55",
        Water_content: "18",
        Health_index: "60.5",
      },
      {
        SL: "16",
        Time: "1:15 AM",
        Hydrogen: "13200",
        Oxygen: "1120",
        Nitrogen: "32800",
        Methane: "2650",
        CO: "156",
        CO2: "2240",
        Ethylene: "16400",
        Ethane: "1610",
        Acethylene: "1510",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "58",
        Water_content: "22",
        Health_index: "60.5",
      },
      {
        SL: "17",
        Time: "1:20 AM",
        Hydrogen: "6620",
        Oxygen: "5250",
        Nitrogen: "51900",
        Methane: "2240",
        CO: "190",
        CO2: "1870",
        Ethylene: "13100",
        Ethane: "1400",
        Acethylene: "1660",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "42",
        Dielectric_rigidity: "54",
        Water_content: "21",
        Health_index: "60.5",
      },
      {
        SL: "18",
        Time: "1:25 AM",
        Hydrogen: "8710",
        Oxygen: "4530",
        Nitrogen: "42800",
        Methane: "658",
        CO: "437",
        CO2: "1780",
        Ethylene: "1260",
        Ethane: "97",
        Acethylene: "9740",
        DBDS: "1",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "55",
        Water_content: "1",
        Health_index: "60.5",
      },
      {
        SL: "19",
        Time: "1:30 AM",
        Hydrogen: "5810",
        Oxygen: "11900",
        Nitrogen: "51400",
        Methane: "471",
        CO: "354",
        CO2: "1470",
        Ethylene: "798",
        Ethane: "44",
        Acethylene: "3990",
        DBDS: "1",
        Power_Factor: "1",
        Interfacial_V: "44",
        Dielectric_rigidity: "50",
        Water_content: "16",
        Health_index: "60.5",
      },
      {
        SL: "20",
        Time: "1:35 AM",
        Hydrogen: "757",
        Oxygen: "289",
        Nitrogen: "57400",
        Methane: "1700",
        CO: "1730",
        CO2: "24900",
        Ethylene: "2280",
        Ethane: "755",
        Acethylene: "12",
        DBDS: "0",
        Power_Factor: "42.1",
        Interfacial_V: "24",
        Dielectric_rigidity: "51",
        Water_content: "77",
        Health_index: "60.5",
      },
      {
        SL: "22",
        Time: "1:45 AM",
        Hydrogen: "1310",
        Oxygen: "2690",
        Nitrogen: "51900",
        Methane: "1010",
        CO: "119",
        CO2: "2220",
        Ethylene: "2520",
        Ethane: "376",
        Acethylene: "17",
        DBDS: "0",
        Power_Factor: "0.25",
        Interfacial_V: "45",
        Dielectric_rigidity: "29",
        Water_content: "34",
        Health_index: "60.5",
      },
      {
        SL: "21",
        Time: "1:40 AM",
        Hydrogen: "590",
        Oxygen: "23200",
        Nitrogen: "63900",
        Methane: "949",
        CO: "209",
        CO2: "51",
        Ethylene: "828",
        Ethane: "168",
        Acethylene: "582",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "55",
        Water_content: "4",
        Health_index: "60.5",
      },
      {
        SL: "23",
        Time: "1:50 AM",
        Hydrogen: "122",
        Oxygen: "294",
        Nitrogen: "73100",
        Methane: "50",
        CO: "372",
        CO2: "2180",
        Ethylene: "69",
        Ethane: "31",
        Acethylene: "0",
        DBDS: "168",
        Power_Factor: "1.27",
        Interfacial_V: "42",
        Dielectric_rigidity: "35",
        Water_content: "19",
        Health_index: "59.3",
      },
      {
        SL: "24",
        Time: "1:55 AM",
        Hydrogen: "106",
        Oxygen: "581",
        Nitrogen: "75200",
        Methane: "47",
        CO: "760",
        CO2: "4070",
        Ethylene: "11",
        Ethane: "30",
        Acethylene: "0",
        DBDS: "183",
        Power_Factor: "0.16",
        Interfacial_V: "43",
        Dielectric_rigidity: "29",
        Water_content: "5",
        Health_index: "58.3",
      },
      {
        SL: "25",
        Time: "2:00 AM",
        Hydrogen: "95",
        Oxygen: "1760",
        Nitrogen: "80800",
        Methane: "72",
        CO: "488",
        CO2: "3050",
        Ethylene: "10",
        Ethane: "36",
        Acethylene: "0",
        DBDS: "176",
        Power_Factor: "0.29",
        Interfacial_V: "44",
        Dielectric_rigidity: "55",
        Water_content: "12",
        Health_index: "58",
      },
      {
        SL: "26",
        Time: "2:05 AM",
        Hydrogen: "87",
        Oxygen: "362",
        Nitrogen: "76100",
        Methane: "47",
        CO: "560",
        CO2: "3920",
        Ethylene: "5",
        Ethane: "31",
        Acethylene: "0",
        DBDS: "184",
        Power_Factor: "0.23",
        Interfacial_V: "43",
        Dielectric_rigidity: "52",
        Water_content: "4",
        Health_index: "57.4",
      },
      {
        SL: "27",
        Time: "2:10 AM",
        Hydrogen: "79",
        Oxygen: "699",
        Nitrogen: "75700",
        Methane: "72",
        CO: "508",
        CO2: "3810",
        Ethylene: "83",
        Ethane: "42",
        Acethylene: "0",
        DBDS: "136",
        Power_Factor: "1.24",
        Interfacial_V: "34",
        Dielectric_rigidity: "48",
        Water_content: "5",
        Health_index: "56",
      },
      {
        SL: "28",
        Time: "2:15 AM",
        Hydrogen: "2183",
        Oxygen: "192",
        Nitrogen: "43380",
        Methane: "1061",
        CO: "183",
        CO2: "5730",
        Ethylene: "1308",
        Ethane: "646",
        Acethylene: "2",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "42",
        Dielectric_rigidity: "28",
        Water_content: "31",
        Health_index: "55.8",
      },
      {
        SL: "29",
        Time: "2:20 AM",
        Hydrogen: "76",
        Oxygen: "324",
        Nitrogen: "71700",
        Methane: "45",
        CO: "904",
        CO2: "5220",
        Ethylene: "10",
        Ethane: "27",
        Acethylene: "0",
        DBDS: "227",
        Power_Factor: "0.45",
        Interfacial_V: "45",
        Dielectric_rigidity: "45",
        Water_content: "8",
        Health_index: "55.1",
      },
      {
        SL: "31",
        Time: "2:30 AM",
        Hydrogen: "14",
        Oxygen: "2750",
        Nitrogen: "29500",
        Methane: "12",
        CO: "54",
        CO2: "5190",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.19",
        Interfacial_V: "43",
        Dielectric_rigidity: "55",
        Water_content: "3",
        Health_index: "51.6",
      },
      {
        SL: "30",
        Time: "2:25 AM",
        Hydrogen: "14",
        Oxygen: "17600",
        Nitrogen: "44300",
        Methane: "0",
        CO: "161",
        CO2: "2010",
        Ethylene: "22",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1.16",
        Interfacial_V: "37",
        Dielectric_rigidity: "49",
        Water_content: "16",
        Health_index: "51.6",
      },
      {
        SL: "32",
        Time: "2:35 AM",
        Hydrogen: "40",
        Oxygen: "2350",
        Nitrogen: "65000",
        Methane: "8",
        CO: "538",
        CO2: "2480",
        Ethylene: "9",
        Ethane: "0",
        Acethylene: "1",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "35",
        Dielectric_rigidity: "56",
        Water_content: "62",
        Health_index: "51.5",
      },
      {
        SL: "33",
        Time: "2:40 AM",
        Hydrogen: "5",
        Oxygen: "9400",
        Nitrogen: "37100",
        Methane: "4",
        CO: "496",
        CO2: "2720",
        Ethylene: "3",
        Ethane: "0",
        Acethylene: "1",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "35",
        Dielectric_rigidity: "56",
        Water_content: "51",
        Health_index: "51.5",
      },
      {
        SL: "34",
        Time: "2:45 AM",
        Hydrogen: "7",
        Oxygen: "12300",
        Nitrogen: "32200",
        Methane: "0",
        CO: "302",
        CO2: "3640",
        Ethylene: "3",
        Ethane: "0",
        Acethylene: "1",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "35",
        Dielectric_rigidity: "55",
        Water_content: "36",
        Health_index: "51.5",
      },
      {
        SL: "36",
        Time: "2:55 AM",
        Hydrogen: "12880",
        Oxygen: "1571",
        Nitrogen: "36351",
        Methane: "827",
        CO: "184",
        CO2: "2267",
        Ethylene: "4",
        Ethane: "320",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1",
        Interfacial_V: "46",
        Dielectric_rigidity: "54",
        Water_content: "12",
        Health_index: "50.7",
      },
      {
        SL: "38",
        Time: "3:05 AM",
        Hydrogen: "921",
        Oxygen: "22000",
        Nitrogen: "43400",
        Methane: "42",
        CO: "132",
        CO2: "542",
        Ethylene: "75",
        Ethane: "3",
        Acethylene: "713",
        DBDS: "0",
        Power_Factor: "0.48",
        Interfacial_V: "45",
        Dielectric_rigidity: "56",
        Water_content: "13",
        Health_index: "50.7",
      },
      {
        SL: "39",
        Time: "3:10 AM",
        Hydrogen: "9350",
        Oxygen: "229",
        Nitrogen: "53000",
        Methane: "188",
        CO: "451",
        CO2: "2720",
        Ethylene: "228",
        Ethane: "28",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "71.75",
        Interfacial_V: "30",
        Dielectric_rigidity: "55",
        Water_content: "5",
        Health_index: "50.7",
      },
      {
        SL: "40",
        Time: "3:15 AM",
        Hydrogen: "6200",
        Oxygen: "291",
        Nitrogen: "59400",
        Methane: "218",
        CO: "492",
        CO2: "10600",
        Ethylene: "103",
        Ethane: "39",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "67.67",
        Interfacial_V: "30",
        Dielectric_rigidity: "54",
        Water_content: "10",
        Health_index: "50.7",
      },
      {
        SL: "41",
        Time: "3:20 AM",
        Hydrogen: "3060",
        Oxygen: "257",
        Nitrogen: "69500",
        Methane: "190",
        CO: "403",
        CO2: "8930",
        Ethylene: "68",
        Ethane: "47",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "73.2",
        Interfacial_V: "29",
        Dielectric_rigidity: "56",
        Water_content: "14",
        Health_index: "50.7",
      },
      {
        SL: "42",
        Time: "3:25 AM",
        Hydrogen: "7907",
        Oxygen: "3564",
        Nitrogen: "24991",
        Methane: "467",
        CO: "96",
        CO2: "1765",
        Ethylene: "2",
        Ethane: "249",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "29",
        Dielectric_rigidity: "56",
        Water_content: "14",
        Health_index: "50.7",
      },
      {
        SL: "43",
        Time: "3:30 AM",
        Hydrogen: "5030",
        Oxygen: "7140",
        Nitrogen: "54300",
        Methane: "179",
        CO: "38",
        CO2: "260",
        Ethylene: "0",
        Ethane: "21",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1.9",
        Interfacial_V: "29",
        Dielectric_rigidity: "49",
        Water_content: "15",
        Health_index: "50.7",
      },
      {
        SL: "44",
        Time: "3:35 AM",
        Hydrogen: "322",
        Oxygen: "669",
        Nitrogen: "56400",
        Methane: "181",
        CO: "614",
        CO2: "466",
        Ethylene: "170",
        Ethane: "15",
        Acethylene: "173",
        DBDS: "0",
        Power_Factor: "0.63",
        Interfacial_V: "45",
        Dielectric_rigidity: "51",
        Water_content: "2",
        Health_index: "50.7",
      },
      {
        SL: "45",
        Time: "3:40 AM",
        Hydrogen: "152",
        Oxygen: "21400",
        Nitrogen: "49300",
        Methane: "254",
        CO: "64",
        CO2: "1510",
        Ethylene: "2250",
        Ethane: "908",
        Acethylene: "4830",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "43",
        Dielectric_rigidity: "51",
        Water_content: "5",
        Health_index: "50.7",
      },
      {
        SL: "37",
        Time: "3:00 AM",
        Hydrogen: "10700",
        Oxygen: "13100",
        Nitrogen: "32700",
        Methane: "625",
        CO: "79",
        CO2: "660",
        Ethylene: "0",
        Ethane: "190",
        Acethylene: "1",
        DBDS: "1",
        Power_Factor: "4.45",
        Interfacial_V: "42",
        Dielectric_rigidity: "44",
        Water_content: "4",
        Health_index: "50.7",
      },
      {
        SL: "35",
        Time: "2:50 AM",
        Hydrogen: "2390",
        Oxygen: "9050",
        Nitrogen: "44300",
        Methane: "163",
        CO: "546",
        CO2: "2660",
        Ethylene: "3",
        Ethane: "53",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1.71",
        Interfacial_V: "46",
        Dielectric_rigidity: "54",
        Water_content: "12",
        Health_index: "50.7",
      },
      {
        SL: "48",
        Time: "3:55 AM",
        Hydrogen: "253",
        Oxygen: "17300",
        Nitrogen: "43700",
        Methane: "135",
        CO: "82",
        CO2: "1870",
        Ethylene: "57",
        Ethane: "734",
        Acethylene: "3330",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "44",
        Dielectric_rigidity: "50",
        Water_content: "4",
        Health_index: "50.6",
      },
      {
        SL: "49",
        Time: "4:00 AM",
        Hydrogen: "216",
        Oxygen: "24300",
        Nitrogen: "48500",
        Methane: "93",
        CO: "94",
        CO2: "1890",
        Ethylene: "578",
        Ethane: "36",
        Acethylene: "2830",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "42",
        Dielectric_rigidity: "54",
        Water_content: "7",
        Health_index: "50.6",
      },
      {
        SL: "46",
        Time: "3:45 AM",
        Hydrogen: "211",
        Oxygen: "249900",
        Nitrogen: "62600",
        Methane: "148",
        CO: "118",
        CO2: "2300",
        Ethylene: "751",
        Ethane: "103",
        Acethylene: "3030",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "41",
        Water_content: "9",
        Health_index: "50.6",
      },
      {
        SL: "47",
        Time: "3:50 AM",
        Hydrogen: "277",
        Oxygen: "21500",
        Nitrogen: "46100",
        Methane: "142",
        CO: "93",
        CO2: "2090",
        Ethylene: "802",
        Ethane: "59",
        Acethylene: "3840",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "50",
        Water_content: "5",
        Health_index: "50.6",
      },
      {
        SL: "50",
        Time: "4:05 AM",
        Hydrogen: "135",
        Oxygen: "5091",
        Nitrogen: "48792",
        Methane: "33",
        CO: "568",
        CO2: "1301",
        Ethylene: "3",
        Ethane: "5",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "0.12",
        Interfacial_V: "47",
        Dielectric_rigidity: "66",
        Water_content: "3",
        Health_index: "50.3",
      },
      {
        SL: "51",
        Time: "4:10 AM",
        Hydrogen: "0",
        Oxygen: "219",
        Nitrogen: "56900",
        Methane: "4",
        CO: "20",
        CO2: "507",
        Ethylene: "30",
        Ethane: "49",
        Acethylene: "67",
        DBDS: "0",
        Power_Factor: "4.4",
        Interfacial_V: "47",
        Dielectric_rigidity: "50",
        Water_content: "3",
        Health_index: "50",
      },
      {
        SL: "52",
        Time: "4:15 AM",
        Hydrogen: "38",
        Oxygen: "3127",
        Nitrogen: "16464",
        Methane: "11",
        CO: "177",
        CO2: "727",
        Ethylene: "28",
        Ethane: "3",
        Acethylene: "19",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "47",
        Dielectric_rigidity: "75",
        Water_content: "38",
        Health_index: "49.9",
      },
      {
        SL: "54",
        Time: "4:25 AM",
        Hydrogen: "30",
        Oxygen: "316",
        Nitrogen: "54100",
        Methane: "161",
        CO: "309",
        CO2: "2710",
        Ethylene: "248",
        Ethane: "28",
        Acethylene: "0",
        DBDS: "20",
        Power_Factor: "0.57",
        Interfacial_V: "40",
        Dielectric_rigidity: "55",
        Water_content: "4",
        Health_index: "49.2",
      },
      {
        SL: "53",
        Time: "4:20 AM",
        Hydrogen: "36",
        Oxygen: "2950",
        Nitrogen: "63300",
        Methane: "101",
        CO: "525",
        CO2: "4080",
        Ethylene: "193",
        Ethane: "35",
        Acethylene: "0",
        DBDS: "127",
        Power_Factor: "0.37",
        Interfacial_V: "40",
        Dielectric_rigidity: "53",
        Water_content: "6",
        Health_index: "49.2",
      },
      {
        SL: "55",
        Time: "4:30 AM",
        Hydrogen: "52",
        Oxygen: "387",
        Nitrogen: "68400",
        Methane: "37",
        CO: "936",
        CO2: "6130",
        Ethylene: "8",
        Ethane: "21",
        Acethylene: "0",
        DBDS: "138",
        Power_Factor: "0.82",
        Interfacial_V: "44",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "49.1",
      },
      {
        SL: "56",
        Time: "4:35 AM",
        Hydrogen: "30",
        Oxygen: "413",
        Nitrogen: "19600",
        Methane: "39",
        CO: "140",
        CO2: "2690",
        Ethylene: "17",
        Ethane: "48",
        Acethylene: "0",
        DBDS: "158",
        Power_Factor: "0.15",
        Interfacial_V: "46",
        Dielectric_rigidity: "56",
        Water_content: "7",
        Health_index: "49",
      },
      {
        SL: "57",
        Time: "4:40 AM",
        Hydrogen: "24",
        Oxygen: "455",
        Nitrogen: "21700",
        Methane: "41",
        CO: "186",
        CO2: "2790",
        Ethylene: "10",
        Ethane: "65",
        Acethylene: "0",
        DBDS: "162",
        Power_Factor: "0.17",
        Interfacial_V: "44",
        Dielectric_rigidity: "52",
        Water_content: "3",
        Health_index: "48.9",
      },
      {
        SL: "59",
        Time: "4:50 AM",
        Hydrogen: "59",
        Oxygen: "645",
        Nitrogen: "56000",
        Methane: "20",
        CO: "267",
        CO2: "2300",
        Ethylene: "9",
        Ethane: "15",
        Acethylene: "0",
        DBDS: "136",
        Power_Factor: "0.21",
        Interfacial_V: "42",
        Dielectric_rigidity: "52",
        Water_content: "4",
        Health_index: "48.5",
      },
      {
        SL: "58",
        Time: "4:45 AM",
        Hydrogen: "21",
        Oxygen: "425",
        Nitrogen: "33000",
        Methane: "32",
        CO: "217",
        CO2: "3030",
        Ethylene: "9",
        Ethane: "47",
        Acethylene: "0",
        DBDS: "160",
        Power_Factor: "0.13",
        Interfacial_V: "42",
        Dielectric_rigidity: "53",
        Water_content: "4",
        Health_index: "48.5",
      },
      {
        SL: "60",
        Time: "4:55 AM",
        Hydrogen: "104",
        Oxygen: "1450",
        Nitrogen: "76500",
        Methane: "37",
        CO: "357",
        CO2: "3220",
        Ethylene: "11",
        Ethane: "11",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.32",
        Interfacial_V: "45",
        Dielectric_rigidity: "54",
        Water_content: "8",
        Health_index: "48.3",
      },
      {
        SL: "77",
        Time: "6:20 AM",
        Hydrogen: "7",
        Oxygen: "1990",
        Nitrogen: "58800",
        Methane: "10",
        CO: "154",
        CO2: "2210",
        Ethylene: "4",
        Ethane: "18",
        Acethylene: "0",
        DBDS: "144",
        Power_Factor: "0.3",
        Interfacial_V: "40",
        Dielectric_rigidity: "50",
        Water_content: "1",
        Health_index: "48.2",
      },
      {
        SL: "78",
        Time: "6:25 AM",
        Hydrogen: "6",
        Oxygen: "3760",
        Nitrogen: "70200",
        Methane: "17",
        CO: "277",
        CO2: "2200",
        Ethylene: "7",
        Ethane: "31",
        Acethylene: "0",
        DBDS: "194",
        Power_Factor: "0.48",
        Interfacial_V: "41",
        Dielectric_rigidity: "55",
        Water_content: "3",
        Health_index: "48.2",
      },
      {
        SL: "83",
        Time: "6:50 AM",
        Hydrogen: "4",
        Oxygen: "57",
        Nitrogen: "31384",
        Methane: "5",
        CO: "89",
        CO2: "876",
        Ethylene: "2",
        Ethane: "6",
        Acethylene: "0",
        DBDS: "76",
        Power_Factor: "0.16",
        Interfacial_V: "38",
        Dielectric_rigidity: "68",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "93",
        Time: "7:40 AM",
        Hydrogen: "0",
        Oxygen: "21200",
        Nitrogen: "44200",
        Methane: "0",
        CO: "91",
        CO2: "1520",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "136",
        Power_Factor: "0.32",
        Interfacial_V: "43",
        Dielectric_rigidity: "50",
        Water_content: "2",
        Health_index: "48.2",
      },
      {
        SL: "102",
        Time: "8:25 AM",
        Hydrogen: "0",
        Oxygen: "21700",
        Nitrogen: "45600",
        Methane: "0",
        CO: "198",
        CO2: "2250",
        Ethylene: "6",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "6",
        Power_Factor: "0.13",
        Interfacial_V: "41",
        Dielectric_rigidity: "55",
        Water_content: "3",
        Health_index: "48.2",
      },
      {
        SL: "108",
        Time: "8:55 AM",
        Hydrogen: "0",
        Oxygen: "14300",
        Nitrogen: "65700",
        Methane: "7",
        CO: "148",
        CO2: "1960",
        Ethylene: "3",
        Ethane: "13",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.41",
        Interfacial_V: "37",
        Dielectric_rigidity: "51",
        Water_content: "2",
        Health_index: "48.2",
      },
      {
        SL: "109",
        Time: "9:00 AM",
        Hydrogen: "18",
        Oxygen: "17600",
        Nitrogen: "51700",
        Methane: "4",
        CO: "231",
        CO2: "1610",
        Ethylene: "0",
        Ethane: "7",
        Acethylene: "0",
        DBDS: "55",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "49",
        Water_content: "3",
        Health_index: "48.2",
      },
      {
        SL: "62",
        Time: "5:05 AM",
        Hydrogen: "40",
        Oxygen: "24800",
        Nitrogen: "53300",
        Methane: "9",
        CO: "84",
        CO2: "919",
        Ethylene: "17",
        Ethane: "12",
        Acethylene: "0",
        DBDS: "88",
        Power_Factor: "1.68",
        Interfacial_V: "39",
        Dielectric_rigidity: "51",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "64",
        Time: "5:15 AM",
        Hydrogen: "3",
        Oxygen: "1900",
        Nitrogen: "81300",
        Methane: "37",
        CO: "234",
        CO2: "2800",
        Ethylene: "10",
        Ethane: "102",
        Acethylene: "0",
        DBDS: "123",
        Power_Factor: "0.44",
        Interfacial_V: "41",
        Dielectric_rigidity: "47",
        Water_content: "6",
        Health_index: "48.2",
      },
      {
        SL: "66",
        Time: "5:25 AM",
        Hydrogen: "28",
        Oxygen: "9950",
        Nitrogen: "47300",
        Methane: "16",
        CO: "245",
        CO2: "1290",
        Ethylene: "0",
        Ethane: "3",
        Acethylene: "0",
        DBDS: "47.5",
        Power_Factor: "0.9",
        Interfacial_V: "44",
        Dielectric_rigidity: "49",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "67",
        Time: "5:30 AM",
        Hydrogen: "25",
        Oxygen: "15500",
        Nitrogen: "50700",
        Methane: "3",
        CO: "267",
        CO2: "1180",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "27",
        Power_Factor: "1",
        Interfacial_V: "43",
        Dielectric_rigidity: "43",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "68",
        Time: "5:35 AM",
        Hydrogen: "25",
        Oxygen: "508",
        Nitrogen: "54500",
        Methane: "12",
        CO: "317",
        CO2: "2750",
        Ethylene: "4",
        Ethane: "14",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.65",
        Interfacial_V: "45",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "72",
        Time: "5:55 AM",
        Hydrogen: "4",
        Oxygen: "408",
        Nitrogen: "38700",
        Methane: "22",
        CO: "105",
        CO2: "1100",
        Ethylene: "7",
        Ethane: "47",
        Acethylene: "0",
        DBDS: "168",
        Power_Factor: "1.82",
        Interfacial_V: "43",
        Dielectric_rigidity: "57",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "74",
        Time: "6:05 AM",
        Hydrogen: "7",
        Oxygen: "376",
        Nitrogen: "54700",
        Methane: "13",
        CO: "205",
        CO2: "1780",
        Ethylene: "4",
        Ethane: "15",
        Acethylene: "0",
        DBDS: "162",
        Power_Factor: "0.29",
        Interfacial_V: "43",
        Dielectric_rigidity: "55",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "79",
        Time: "6:30 AM",
        Hydrogen: "5",
        Oxygen: "378",
        Nitrogen: "53100",
        Methane: "16",
        CO: "231",
        CO2: "2170",
        Ethylene: "5",
        Ethane: "22",
        Acethylene: "0",
        DBDS: "165",
        Power_Factor: "0.32",
        Interfacial_V: "43",
        Dielectric_rigidity: "54",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "94",
        Time: "7:45 AM",
        Hydrogen: "0",
        Oxygen: "25900",
        Nitrogen: "49700",
        Methane: "0",
        CO: "22",
        CO2: "399",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "120",
        Power_Factor: "0.86",
        Interfacial_V: "39",
        Dielectric_rigidity: "50",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "95",
        Time: "7:50 AM",
        Hydrogen: "0",
        Oxygen: "22900",
        Nitrogen: "45300",
        Methane: "0",
        CO: "66",
        CO2: "553",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "155",
        Power_Factor: "0.37",
        Interfacial_V: "43",
        Dielectric_rigidity: "53",
        Water_content: "5",
        Health_index: "48.2",
      },
      {
        SL: "96",
        Time: "7:55 AM",
        Hydrogen: "0",
        Oxygen: "21800",
        Nitrogen: "52500",
        Methane: "3",
        CO: "78",
        CO2: "2180",
        Ethylene: "9",
        Ethane: "8",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.41",
        Interfacial_V: "42",
        Dielectric_rigidity: "56",
        Water_content: "6",
        Health_index: "48.2",
      },
      {
        SL: "97",
        Time: "8:00 AM",
        Hydrogen: "0",
        Oxygen: "2220",
        Nitrogen: "58800",
        Methane: "13",
        CO: "131",
        CO2: "1520",
        Ethylene: "4",
        Ethane: "22",
        Acethylene: "0",
        DBDS: "173",
        Power_Factor: "0.55",
        Interfacial_V: "42",
        Dielectric_rigidity: "52",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "98",
        Time: "8:05 AM",
        Hydrogen: "0",
        Oxygen: "944",
        Nitrogen: "58700",
        Methane: "6",
        CO: "266",
        CO2: "3530",
        Ethylene: "8",
        Ethane: "11",
        Acethylene: "0",
        DBDS: "153",
        Power_Factor: "0.35",
        Interfacial_V: "40",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "99",
        Time: "8:10 AM",
        Hydrogen: "0",
        Oxygen: "27000",
        Nitrogen: "56600",
        Methane: "0",
        CO: "47",
        CO2: "480",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "11",
        Power_Factor: "1",
        Interfacial_V: "43",
        Dielectric_rigidity: "51",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "100",
        Time: "8:15 AM",
        Hydrogen: "0",
        Oxygen: "21600",
        Nitrogen: "45800",
        Methane: "0",
        CO: "204",
        CO2: "2750",
        Ethylene: "5",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "9",
        Power_Factor: "0.08",
        Interfacial_V: "43",
        Dielectric_rigidity: "52",
        Water_content: "6",
        Health_index: "48.2",
      },
      {
        SL: "106",
        Time: "8:45 AM",
        Hydrogen: "0",
        Oxygen: "24800",
        Nitrogen: "45700",
        Methane: "0",
        CO: "81",
        CO2: "514",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "203",
        Power_Factor: "1.47",
        Interfacial_V: "45",
        Dielectric_rigidity: "55",
        Water_content: "5",
        Health_index: "48.2",
      },
      {
        SL: "107",
        Time: "8:50 AM",
        Hydrogen: "0",
        Oxygen: "22000",
        Nitrogen: "44900",
        Methane: "0",
        CO: "122",
        CO2: "856",
        Ethylene: "8",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "136",
        Power_Factor: "0.63",
        Interfacial_V: "41",
        Dielectric_rigidity: "52",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "73",
        Time: "6:00 AM",
        Hydrogen: "8",
        Oxygen: "1060",
        Nitrogen: "55300",
        Methane: "14",
        CO: "235",
        CO2: "1850",
        Ethylene: "6",
        Ethane: "22",
        Acethylene: "0",
        DBDS: "113",
        Power_Factor: "0.21",
        Interfacial_V: "42",
        Dielectric_rigidity: "56",
        Water_content: "3",
        Health_index: "48.2",
      },
      {
        SL: "89",
        Time: "7:20 AM",
        Hydrogen: "2",
        Oxygen: "21500",
        Nitrogen: "47500",
        Methane: "2",
        CO: "106",
        CO2: "1040",
        Ethylene: "3",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "123",
        Power_Factor: "0.28",
        Interfacial_V: "42",
        Dielectric_rigidity: "54",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "101",
        Time: "8:20 AM",
        Hydrogen: "0",
        Oxygen: "30800",
        Nitrogen: "58700",
        Methane: "0",
        CO: "98",
        CO2: "1740",
        Ethylene: "4",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "6",
        Power_Factor: "0.17",
        Interfacial_V: "44",
        Dielectric_rigidity: "53",
        Water_content: "4",
        Health_index: "48.2",
      },
      {
        SL: "61",
        Time: "5:00 AM",
        Hydrogen: "3",
        Oxygen: "19700",
        Nitrogen: "67600",
        Methane: "0",
        CO: "108",
        CO2: "1480",
        Ethylene: "10",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "17",
        Power_Factor: "1",
        Interfacial_V: "43",
        Dielectric_rigidity: "53",
        Water_content: "28",
        Health_index: "48.2",
      },
      {
        SL: "63",
        Time: "5:10 AM",
        Hydrogen: "35",
        Oxygen: "1920",
        Nitrogen: "73500",
        Methane: "6",
        CO: "202",
        CO2: "1310",
        Ethylene: "20",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "92.6",
        Power_Factor: "0.48",
        Interfacial_V: "40",
        Dielectric_rigidity: "49",
        Water_content: "8",
        Health_index: "48.2",
      },
      {
        SL: "69",
        Time: "5:40 AM",
        Hydrogen: "23",
        Oxygen: "888",
        Nitrogen: "74700",
        Methane: "16",
        CO: "914",
        CO2: "3420",
        Ethylene: "5",
        Ethane: "6",
        Acethylene: "0",
        DBDS: "63.7",
        Power_Factor: "0.14",
        Interfacial_V: "43",
        Dielectric_rigidity: "47",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "70",
        Time: "5:45 AM",
        Hydrogen: "9",
        Oxygen: "10700",
        Nitrogen: "42300",
        Methane: "2",
        CO: "308",
        CO2: "1970",
        Ethylene: "0",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "108",
        Power_Factor: "0.38",
        Interfacial_V: "42",
        Dielectric_rigidity: "57",
        Water_content: "9",
        Health_index: "48.2",
      },
      {
        SL: "71",
        Time: "5:50 AM",
        Hydrogen: "9",
        Oxygen: "738",
        Nitrogen: "56000",
        Methane: "10",
        CO: "294",
        CO2: "1960",
        Ethylene: "4",
        Ethane: "17",
        Acethylene: "0",
        DBDS: "175",
        Power_Factor: "0.27",
        Interfacial_V: "42",
        Dielectric_rigidity: "56",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "75",
        Time: "6:10 AM",
        Hydrogen: "7",
        Oxygen: "425",
        Nitrogen: "50500",
        Methane: "9",
        CO: "317",
        CO2: "2690",
        Ethylene: "4",
        Ethane: "15",
        Acethylene: "0",
        DBDS: "165",
        Power_Factor: "0.32",
        Interfacial_V: "41",
        Dielectric_rigidity: "55",
        Water_content: "8",
        Health_index: "48.2",
      },
      {
        SL: "76",
        Time: "6:15 AM",
        Hydrogen: "7",
        Oxygen: "15700",
        Nitrogen: "46800",
        Methane: "2",
        CO: "373",
        CO2: "3470",
        Ethylene: "28",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "162",
        Power_Factor: "0.57",
        Interfacial_V: "40",
        Dielectric_rigidity: "51",
        Water_content: "8",
        Health_index: "48.2",
      },
      {
        SL: "80",
        Time: "6:35 AM",
        Hydrogen: "5",
        Oxygen: "17400",
        Nitrogen: "53400",
        Methane: "4",
        CO: "296",
        CO2: "2750",
        Ethylene: "7",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "164",
        Power_Factor: "0.52",
        Interfacial_V: "41",
        Dielectric_rigidity: "55",
        Water_content: "10",
        Health_index: "48.2",
      },
      {
        SL: "81",
        Time: "6:40 AM",
        Hydrogen: "5",
        Oxygen: "22900",
        Nitrogen: "51800",
        Methane: "0",
        CO: "149",
        CO2: "826",
        Ethylene: "10",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "12",
        Power_Factor: "0.21",
        Interfacial_V: "40",
        Dielectric_rigidity: "49",
        Water_content: "10",
        Health_index: "48.2",
      },
      {
        SL: "82",
        Time: "6:45 AM",
        Hydrogen: "5",
        Oxygen: "20400",
        Nitrogen: "42200",
        Methane: "0",
        CO: "148",
        CO2: "820",
        Ethylene: "17",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "142",
        Power_Factor: "1.02",
        Interfacial_V: "38",
        Dielectric_rigidity: "52",
        Water_content: "9",
        Health_index: "48.2",
      },
      {
        SL: "84",
        Time: "6:55 AM",
        Hydrogen: "4",
        Oxygen: "4740",
        Nitrogen: "73200",
        Methane: "2",
        CO: "154",
        CO2: "1910",
        Ethylene: "8",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "7",
        Power_Factor: "1.55",
        Interfacial_V: "40",
        Dielectric_rigidity: "52",
        Water_content: "15",
        Health_index: "48.2",
      },
      {
        SL: "85",
        Time: "7:00 AM",
        Hydrogen: "4",
        Oxygen: "20200",
        Nitrogen: "44700",
        Methane: "0",
        CO: "194",
        CO2: "2050",
        Ethylene: "66",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "144",
        Power_Factor: "2.05",
        Interfacial_V: "37",
        Dielectric_rigidity: "54",
        Water_content: "13",
        Health_index: "48.2",
      },
      {
        SL: "86",
        Time: "7:05 AM",
        Hydrogen: "3",
        Oxygen: "15400",
        Nitrogen: "46100",
        Methane: "0",
        CO: "333",
        CO2: "1240",
        Ethylene: "18",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1.49",
        Interfacial_V: "38",
        Dielectric_rigidity: "35",
        Water_content: "14",
        Health_index: "48.2",
      },
      {
        SL: "87",
        Time: "7:10 AM",
        Hydrogen: "3",
        Oxygen: "20600",
        Nitrogen: "42000",
        Methane: "0",
        CO: "118",
        CO2: "906",
        Ethylene: "18",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "127",
        Power_Factor: "0.89",
        Interfacial_V: "37",
        Dielectric_rigidity: "57",
        Water_content: "6",
        Health_index: "48.2",
      },
      {
        SL: "88",
        Time: "7:15 AM",
        Hydrogen: "3",
        Oxygen: "395",
        Nitrogen: "47000",
        Methane: "5",
        CO: "47",
        CO2: "623",
        Ethylene: "9",
        Ethane: "11",
        Acethylene: "0",
        DBDS: "169",
        Power_Factor: "3.35",
        Interfacial_V: "38",
        Dielectric_rigidity: "54",
        Water_content: "9",
        Health_index: "48.2",
      },
      {
        SL: "90",
        Time: "7:25 AM",
        Hydrogen: "2",
        Oxygen: "14700",
        Nitrogen: "44200",
        Methane: "2",
        CO: "297",
        CO2: "1780",
        Ethylene: "55",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "35",
        Power_Factor: "0.8",
        Interfacial_V: "41",
        Dielectric_rigidity: "41",
        Water_content: "14",
        Health_index: "48.2",
      },
      {
        SL: "91",
        Time: "7:30 AM",
        Hydrogen: "0",
        Oxygen: "5640",
        Nitrogen: "71800",
        Methane: "17",
        CO: "305",
        CO2: "2200",
        Ethylene: "6",
        Ethane: "41",
        Acethylene: "0",
        DBDS: "4.4",
        Power_Factor: "0.23",
        Interfacial_V: "42",
        Dielectric_rigidity: "55",
        Water_content: "6",
        Health_index: "48.2",
      },
      {
        SL: "92",
        Time: "7:35 AM",
        Hydrogen: "0",
        Oxygen: "21900",
        Nitrogen: "48300",
        Methane: "2",
        CO: "39",
        CO2: "1420",
        Ethylene: "3",
        Ethane: "7",
        Acethylene: "0",
        DBDS: "136",
        Power_Factor: "0.41",
        Interfacial_V: "41",
        Dielectric_rigidity: "56",
        Water_content: "9",
        Health_index: "48.2",
      },
      {
        SL: "103",
        Time: "8:30 AM",
        Hydrogen: "0",
        Oxygen: "8380",
        Nitrogen: "30800",
        Methane: "0",
        CO: "23",
        CO2: "180",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "9.43",
        Interfacial_V: "37",
        Dielectric_rigidity: "43",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "104",
        Time: "8:35 AM",
        Hydrogen: "0",
        Oxygen: "27300",
        Nitrogen: "55500",
        Methane: "0",
        CO: "32",
        CO2: "525",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "0.62",
        Interfacial_V: "40",
        Dielectric_rigidity: "40",
        Water_content: "19",
        Health_index: "48.2",
      },
      {
        SL: "105",
        Time: "8:40 AM",
        Hydrogen: "0",
        Oxygen: "19300",
        Nitrogen: "45700",
        Methane: "0",
        CO: "53",
        CO2: "481",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1.24",
        Interfacial_V: "45",
        Dielectric_rigidity: "47",
        Water_content: "6",
        Health_index: "48.2",
      },
      {
        SL: "110",
        Time: "9:05 AM",
        Hydrogen: "11",
        Oxygen: "1140",
        Nitrogen: "63900",
        Methane: "7",
        CO: "540",
        CO2: "2980",
        Ethylene: "47",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "60",
        Power_Factor: "8.44",
        Interfacial_V: "36",
        Dielectric_rigidity: "50",
        Water_content: "36",
        Health_index: "48.2",
      },
      {
        SL: "111",
        Time: "9:10 AM",
        Hydrogen: "16",
        Oxygen: "7340",
        Nitrogen: "71000",
        Methane: "5",
        CO: "548",
        CO2: "3170",
        Ethylene: "5",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.36",
        Interfacial_V: "46",
        Dielectric_rigidity: "45",
        Water_content: "8",
        Health_index: "48.2",
      },
      {
        SL: "112",
        Time: "9:15 AM",
        Hydrogen: "12",
        Oxygen: "461",
        Nitrogen: "54500",
        Methane: "3",
        CO: "69",
        CO2: "2150",
        Ethylene: "3",
        Ethane: "8",
        Acethylene: "0",
        DBDS: "161",
        Power_Factor: "0.28",
        Interfacial_V: "41",
        Dielectric_rigidity: "57",
        Water_content: "7",
        Health_index: "48.2",
      },
      {
        SL: "65",
        Time: "5:20 AM",
        Hydrogen: "0",
        Oxygen: "693",
        Nitrogen: "50600",
        Methane: "43",
        CO: "68",
        CO2: "2770",
        Ethylene: "4",
        Ethane: "91",
        Acethylene: "0",
        DBDS: "180",
        Power_Factor: "1.15",
        Interfacial_V: "44",
        Dielectric_rigidity: "52",
        Water_content: "10",
        Health_index: "48.2",
      },
      {
        SL: "113",
        Time: "9:20 AM",
        Hydrogen: "4",
        Oxygen: "624",
        Nitrogen: "44500",
        Methane: "36",
        CO: "232",
        CO2: "2580",
        Ethylene: "3",
        Ethane: "54",
        Acethylene: "0",
        DBDS: "169",
        Power_Factor: "1.16",
        Interfacial_V: "42",
        Dielectric_rigidity: "56",
        Water_content: "8",
        Health_index: "48.1",
      },
      {
        SL: "114",
        Time: "9:25 AM",
        Hydrogen: "114",
        Oxygen: "2359",
        Nitrogen: "31861",
        Methane: "2",
        CO: "144",
        CO2: "707",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "42",
        Dielectric_rigidity: "75",
        Water_content: "28",
        Health_index: "47.9",
      },
      {
        SL: "115",
        Time: "9:30 AM",
        Hydrogen: "1450",
        Oxygen: "13000",
        Nitrogen: "55800",
        Methane: "157",
        CO: "278",
        CO2: "3360",
        Ethylene: "82",
        Ethane: "75",
        Acethylene: "0",
        DBDS: "3",
        Power_Factor: "13.8",
        Interfacial_V: "36",
        Dielectric_rigidity: "56",
        Water_content: "6",
        Health_index: "46.6",
      },
      {
        SL: "116",
        Time: "9:35 AM",
        Hydrogen: "81",
        Oxygen: "23790",
        Nitrogen: "64479",
        Methane: "10",
        CO: "852",
        CO2: "1371",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.06",
        Interfacial_V: "47",
        Dielectric_rigidity: "74",
        Water_content: "4",
        Health_index: "45.3",
      },
      {
        SL: "117",
        Time: "9:40 AM",
        Hydrogen: "67",
        Oxygen: "5940",
        Nitrogen: "41600",
        Methane: "14",
        CO: "930",
        CO2: "4030",
        Ethylene: "0",
        Ethane: "5",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.15",
        Interfacial_V: "43",
        Dielectric_rigidity: "50",
        Water_content: "2",
        Health_index: "40",
      },
      {
        SL: "118",
        Time: "9:45 AM",
        Hydrogen: "1230",
        Oxygen: "239",
        Nitrogen: "71300",
        Methane: "61",
        CO: "576",
        CO2: "11300",
        Ethylene: "28",
        Ethane: "24",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.95",
        Interfacial_V: "34",
        Dielectric_rigidity: "53",
        Water_content: "12",
        Health_index: "38.6",
      },
      {
        SL: "119",
        Time: "9:50 AM",
        Hydrogen: "54",
        Oxygen: "1690",
        Nitrogen: "27100",
        Methane: "8",
        CO: "554",
        CO2: "3990",
        Ethylene: "0",
        Ethane: "3",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.19",
        Interfacial_V: "45",
        Dielectric_rigidity: "56",
        Water_content: "2",
        Health_index: "38.4",
      },
      {
        SL: "121",
        Time: "10:00 AM",
        Hydrogen: "37",
        Oxygen: "623",
        Nitrogen: "20300",
        Methane: "21",
        CO: "888",
        CO2: "3690",
        Ethylene: "10",
        Ethane: "10",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.14",
        Interfacial_V: "44",
        Dielectric_rigidity: "55",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "120",
        Time: "9:55 AM",
        Hydrogen: "44",
        Oxygen: "1735",
        Nitrogen: "41280",
        Methane: "1",
        CO: "133",
        CO2: "520",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "74",
        Water_content: "24",
        Health_index: "38.3",
      },
      {
        SL: "122",
        Time: "10:05 AM",
        Hydrogen: "24",
        Oxygen: "35700",
        Nitrogen: "85300",
        Methane: "5",
        CO: "361",
        CO2: "1570",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.09",
        Interfacial_V: "40",
        Dielectric_rigidity: "55",
        Water_content: "7",
        Health_index: "38.3",
      },
      {
        SL: "127",
        Time: "10:30 AM",
        Hydrogen: "8",
        Oxygen: "10600",
        Nitrogen: "61600",
        Methane: "23",
        CO: "226",
        CO2: "4390",
        Ethylene: "0",
        Ethane: "5",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.13",
        Interfacial_V: "45",
        Dielectric_rigidity: "52",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "129",
        Time: "10:40 AM",
        Hydrogen: "7",
        Oxygen: "4973",
        Nitrogen: "56032",
        Methane: "21",
        CO: "200",
        CO2: "4782",
        Ethylene: "0",
        Ethane: "2",
        Acethylene: "0",
        DBDS: "10",
        Power_Factor: "0.21",
        Interfacial_V: "38",
        Dielectric_rigidity: "66",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "131",
        Time: "10:50 AM",
        Hydrogen: "9",
        Oxygen: "909",
        Nitrogen: "32800",
        Methane: "16",
        CO: "279",
        CO2: "2820",
        Ethylene: "0",
        Ethane: "3",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.12",
        Interfacial_V: "45",
        Dielectric_rigidity: "49",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "132",
        Time: "10:55 AM",
        Hydrogen: "7",
        Oxygen: "8220",
        Nitrogen: "55800",
        Methane: "18",
        CO: "236",
        CO2: "2730",
        Ethylene: "0",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.08",
        Interfacial_V: "54",
        Dielectric_rigidity: "52",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "134",
        Time: "11:05 AM",
        Hydrogen: "7",
        Oxygen: "1430",
        Nitrogen: "15400",
        Methane: "4",
        CO: "221",
        CO2: "268",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "1.58",
        Interfacial_V: "46",
        Dielectric_rigidity: "48",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "135",
        Time: "11:10 AM",
        Hydrogen: "7",
        Oxygen: "2630",
        Nitrogen: "58800",
        Methane: "2",
        CO: "784",
        CO2: "1410",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.26",
        Interfacial_V: "40",
        Dielectric_rigidity: "46",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "138",
        Time: "11:25 AM",
        Hydrogen: "6",
        Oxygen: "13300",
        Nitrogen: "36900",
        Methane: "0",
        CO: "411",
        CO2: "4160",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "41",
        Dielectric_rigidity: "52",
        Water_content: "55",
        Health_index: "38.3",
      },
      {
        SL: "139",
        Time: "11:30 AM",
        Hydrogen: "6",
        Oxygen: "6080",
        Nitrogen: "40900",
        Methane: "5",
        CO: "893",
        CO2: "2640",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "33",
        Dielectric_rigidity: "55",
        Water_content: "12",
        Health_index: "38.3",
      },
      {
        SL: "140",
        Time: "11:35 AM",
        Hydrogen: "5",
        Oxygen: "12300",
        Nitrogen: "70900",
        Methane: "17",
        CO: "269",
        CO2: "1880",
        Ethylene: "3",
        Ethane: "5",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.12",
        Interfacial_V: "45",
        Dielectric_rigidity: "48",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "141",
        Time: "11:40 AM",
        Hydrogen: "5",
        Oxygen: "12500",
        Nitrogen: "48400",
        Methane: "3",
        CO: "534",
        CO2: "3010",
        Ethylene: "3",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "62",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "145",
        Time: "12:00 PM",
        Hydrogen: "4",
        Oxygen: "13600",
        Nitrogen: "37500",
        Methane: "3",
        CO: "443",
        CO2: "5890",
        Ethylene: "0",
        Ethane: "7",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "34",
        Dielectric_rigidity: "55",
        Water_content: "77",
        Health_index: "38.3",
      },
      {
        SL: "147",
        Time: "12:10 PM",
        Hydrogen: "3",
        Oxygen: "20500",
        Nitrogen: "44000",
        Methane: "0",
        CO: "35",
        CO2: "290",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1",
        Interfacial_V: "47",
        Dielectric_rigidity: "48",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "148",
        Time: "12:15 PM",
        Hydrogen: "3",
        Oxygen: "17400",
        Nitrogen: "56700",
        Methane: "3",
        CO: "362",
        CO2: "2230",
        Ethylene: "4",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1.02",
        Interfacial_V: "44",
        Dielectric_rigidity: "48",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "149",
        Time: "12:20 PM",
        Hydrogen: "3",
        Oxygen: "2020",
        Nitrogen: "59600",
        Methane: "6",
        CO: "1070",
        CO2: "2950",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.39",
        Interfacial_V: "42",
        Dielectric_rigidity: "51",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "157",
        Time: "1:00 PM",
        Hydrogen: "2",
        Oxygen: "24978",
        Nitrogen: "76582",
        Methane: "2",
        CO: "19",
        CO2: "498",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "48",
        Dielectric_rigidity: "55",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "162",
        Time: "1:25 PM",
        Hydrogen: "0",
        Oxygen: "7520",
        Nitrogen: "38100",
        Methane: "5",
        CO: "297",
        CO2: "778",
        Ethylene: "0",
        Ethane: "3",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.39",
        Interfacial_V: "44",
        Dielectric_rigidity: "47",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "163",
        Time: "1:30 PM",
        Hydrogen: "0",
        Oxygen: "839",
        Nitrogen: "20700",
        Methane: "4",
        CO: "458",
        CO2: "2830",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "0.46",
        Interfacial_V: "41",
        Dielectric_rigidity: "47",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "164",
        Time: "1:35 PM",
        Hydrogen: "0",
        Oxygen: "1565",
        Nitrogen: "9555",
        Methane: "0",
        CO: "111",
        CO2: "417",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.26",
        Interfacial_V: "42",
        Dielectric_rigidity: "75",
        Water_content: "7",
        Health_index: "38.3",
      },
      {
        SL: "166",
        Time: "1:45 PM",
        Hydrogen: "0",
        Oxygen: "21800",
        Nitrogen: "47300",
        Methane: "0",
        CO: "249",
        CO2: "2510",
        Ethylene: "7",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.27",
        Interfacial_V: "44",
        Dielectric_rigidity: "49",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "168",
        Time: "1:55 PM",
        Hydrogen: "0",
        Oxygen: "26600",
        Nitrogen: "62500",
        Methane: "2",
        CO: "209",
        CO2: "2190",
        Ethylene: "6",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.07",
        Interfacial_V: "46",
        Dielectric_rigidity: "52",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "169",
        Time: "2:00 PM",
        Hydrogen: "0",
        Oxygen: "3300",
        Nitrogen: "12200",
        Methane: "0",
        CO: "118",
        CO2: "270",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1",
        Interfacial_V: "45",
        Dielectric_rigidity: "56",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "173",
        Time: "2:20 PM",
        Hydrogen: "0",
        Oxygen: "25200",
        Nitrogen: "50000",
        Methane: "0",
        CO: "67",
        CO2: "462",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.31",
        Interfacial_V: "48",
        Dielectric_rigidity: "54",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "174",
        Time: "2:25 PM",
        Hydrogen: "11",
        Oxygen: "478",
        Nitrogen: "19400",
        Methane: "11",
        CO: "196",
        CO2: "1900",
        Ethylene: "3",
        Ethane: "5",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.37",
        Interfacial_V: "43",
        Dielectric_rigidity: "42",
        Water_content: "2",
        Health_index: "38.3",
      },
      {
        SL: "126",
        Time: "10:25 AM",
        Hydrogen: "19",
        Oxygen: "618",
        Nitrogen: "20200",
        Methane: "15",
        CO: "184",
        CO2: "586",
        Ethylene: "2",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.36",
        Interfacial_V: "47",
        Dielectric_rigidity: "47",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "128",
        Time: "10:35 AM",
        Hydrogen: "8",
        Oxygen: "8710",
        Nitrogen: "71900",
        Methane: "21",
        CO: "230",
        CO2: "5050",
        Ethylene: "0",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "10",
        Power_Factor: "0.2",
        Interfacial_V: "43",
        Dielectric_rigidity: "55",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "133",
        Time: "11:00 AM",
        Hydrogen: "7",
        Oxygen: "647",
        Nitrogen: "16900",
        Methane: "8",
        CO: "152",
        CO2: "528",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.11",
        Interfacial_V: "45",
        Dielectric_rigidity: "47",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "161",
        Time: "1:20 PM",
        Hydrogen: "0",
        Oxygen: "5010",
        Nitrogen: "51800",
        Methane: "4",
        CO: "262",
        CO2: "845",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.41",
        Interfacial_V: "45",
        Dielectric_rigidity: "52",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "175",
        Time: "2:30 PM",
        Hydrogen: "17",
        Oxygen: "5680",
        Nitrogen: "59500",
        Methane: "16",
        CO: "809",
        CO2: "3590",
        Ethylene: "11",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.35",
        Interfacial_V: "42",
        Dielectric_rigidity: "50",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "123",
        Time: "10:10 AM",
        Hydrogen: "24",
        Oxygen: "1330",
        Nitrogen: "70800",
        Methane: "12",
        CO: "771",
        CO2: "2960",
        Ethylene: "3",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.12",
        Interfacial_V: "44",
        Dielectric_rigidity: "50",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "124",
        Time: "10:15 AM",
        Hydrogen: "22",
        Oxygen: "2820",
        Nitrogen: "53100",
        Methane: "3",
        CO: "770",
        CO2: "2390",
        Ethylene: "3",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "11",
        Power_Factor: "0.37",
        Interfacial_V: "43",
        Dielectric_rigidity: "43",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "125",
        Time: "10:20 AM",
        Hydrogen: "20",
        Oxygen: "2170",
        Nitrogen: "21300",
        Methane: "6",
        CO: "307",
        CO2: "1960",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1.02",
        Interfacial_V: "46",
        Dielectric_rigidity: "52",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "130",
        Time: "10:45 AM",
        Hydrogen: "10",
        Oxygen: "3350",
        Nitrogen: "51100",
        Methane: "2",
        CO: "678",
        CO2: "2360",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.24",
        Interfacial_V: "44",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "137",
        Time: "11:20 AM",
        Hydrogen: "6",
        Oxygen: "8510",
        Nitrogen: "64300",
        Methane: "13",
        CO: "291",
        CO2: "2050",
        Ethylene: "9",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "0.72",
        Interfacial_V: "41",
        Dielectric_rigidity: "50",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "144",
        Time: "11:55 AM",
        Hydrogen: "4",
        Oxygen: "279",
        Nitrogen: "20000",
        Methane: "8",
        CO: "285",
        CO2: "4230",
        Ethylene: "0",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.22",
        Interfacial_V: "44",
        Dielectric_rigidity: "55",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "146",
        Time: "12:05 PM",
        Hydrogen: "4",
        Oxygen: "17000",
        Nitrogen: "56700",
        Methane: "1",
        CO: "408",
        CO2: "936",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.54",
        Interfacial_V: "47",
        Dielectric_rigidity: "48",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "150",
        Time: "12:25 PM",
        Hydrogen: "3",
        Oxygen: "22900",
        Nitrogen: "48000",
        Methane: "0",
        CO: "201",
        CO2: "2320",
        Ethylene: "5",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "3",
        Power_Factor: "0.1",
        Interfacial_V: "45",
        Dielectric_rigidity: "51",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "151",
        Time: "12:30 PM",
        Hydrogen: "3",
        Oxygen: "23700",
        Nitrogen: "49800",
        Methane: "0",
        CO: "202",
        CO2: "3290",
        Ethylene: "8",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.1",
        Interfacial_V: "46",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "155",
        Time: "12:50 PM",
        Hydrogen: "3",
        Oxygen: "14900",
        Nitrogen: "56700",
        Methane: "0",
        CO: "163",
        CO2: "458",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.13",
        Interfacial_V: "44",
        Dielectric_rigidity: "50",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "156",
        Time: "12:55 PM",
        Hydrogen: "3",
        Oxygen: "12000",
        Nitrogen: "35800",
        Methane: "0",
        CO: "195",
        CO2: "283",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.59",
        Interfacial_V: "48",
        Dielectric_rigidity: "55",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "158",
        Time: "1:05 PM",
        Hydrogen: "2",
        Oxygen: "15900",
        Nitrogen: "51300",
        Methane: "4",
        CO: "359",
        CO2: "2250",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.23",
        Interfacial_V: "43",
        Dielectric_rigidity: "49",
        Water_content: "3",
        Health_index: "38.3",
      },
      {
        SL: "159",
        Time: "1:10 PM",
        Hydrogen: "2",
        Oxygen: "24800",
        Nitrogen: "54600",
        Methane: "3",
        CO: "216",
        CO2: "3260",
        Ethylene: "9",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "4",
        Power_Factor: "0.08",
        Interfacial_V: "46",
        Dielectric_rigidity: "54",
        Water_content: "6",
        Health_index: "38.3",
      },
      {
        SL: "165",
        Time: "1:40 PM",
        Hydrogen: "0",
        Oxygen: "22200",
        Nitrogen: "47200",
        Methane: "2",
        CO: "223",
        CO2: "2650",
        Ethylene: "10",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "4",
        Power_Factor: "0.25",
        Interfacial_V: "45",
        Dielectric_rigidity: "55",
        Water_content: "6",
        Health_index: "38.3",
      },
      {
        SL: "167",
        Time: "1:50 PM",
        Hydrogen: "0",
        Oxygen: "22900",
        Nitrogen: "49800",
        Methane: "0",
        CO: "205",
        CO2: "2190",
        Ethylene: "5",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "2",
        Power_Factor: "0.09",
        Interfacial_V: "50",
        Dielectric_rigidity: "50",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "170",
        Time: "2:05 PM",
        Hydrogen: "0",
        Oxygen: "1850",
        Nitrogen: "61700",
        Methane: "0",
        CO: "43",
        CO2: "554",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "3.93",
        Interfacial_V: "51",
        Dielectric_rigidity: "51",
        Water_content: "5",
        Health_index: "38.3",
      },
      {
        SL: "172",
        Time: "2:15 PM",
        Hydrogen: "0",
        Oxygen: "24400",
        Nitrogen: "47700",
        Methane: "0",
        CO: "51",
        CO2: "458",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.32",
        Interfacial_V: "46",
        Dielectric_rigidity: "56",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "136",
        Time: "11:15 AM",
        Hydrogen: "7",
        Oxygen: "4520",
        Nitrogen: "22800",
        Methane: "2",
        CO: "157",
        CO2: "1080",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "1.55",
        Interfacial_V: "46",
        Dielectric_rigidity: "49",
        Water_content: "7",
        Health_index: "38.3",
      },
      {
        SL: "142",
        Time: "11:45 AM",
        Hydrogen: "5",
        Oxygen: "3686",
        Nitrogen: "57725",
        Methane: "5",
        CO: "158",
        CO2: "4331",
        Ethylene: "6",
        Ethane: "1",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "1.41",
        Interfacial_V: "39",
        Dielectric_rigidity: "49",
        Water_content: "19",
        Health_index: "38.3",
      },
      {
        SL: "143",
        Time: "11:50 AM",
        Hydrogen: "5",
        Oxygen: "15000",
        Nitrogen: "44400",
        Methane: "0",
        CO: "230",
        CO2: "399",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.71",
        Interfacial_V: "48",
        Dielectric_rigidity: "57",
        Water_content: "4",
        Health_index: "38.3",
      },
      {
        SL: "154",
        Time: "12:45 PM",
        Hydrogen: "3",
        Oxygen: "18400",
        Nitrogen: "45000",
        Methane: "0",
        CO: "128",
        CO2: "1700",
        Ethylene: "28",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "1.7",
        Interfacial_V: "35",
        Dielectric_rigidity: "55",
        Water_content: "12",
        Health_index: "38.3",
      },
      {
        SL: "160",
        Time: "1:15 PM",
        Hydrogen: "0",
        Oxygen: "24600",
        Nitrogen: "50800",
        Methane: "0",
        CO: "31",
        CO2: "907",
        Ethylene: "9",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1.05",
        Interfacial_V: "41",
        Dielectric_rigidity: "53",
        Water_content: "8",
        Health_index: "38.3",
      },
      {
        SL: "171",
        Time: "2:10 PM",
        Hydrogen: "0",
        Oxygen: "27200",
        Nitrogen: "58900",
        Methane: "0",
        CO: "100",
        CO2: "609",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1.93",
        Interfacial_V: "38",
        Dielectric_rigidity: "52",
        Water_content: "8",
        Health_index: "38.3",
      },
      {
        SL: "176",
        Time: "2:35 PM",
        Hydrogen: "12",
        Oxygen: "15200",
        Nitrogen: "62800",
        Methane: "4",
        CO: "413",
        CO2: "4720",
        Ethylene: "5",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.53",
        Interfacial_V: "44",
        Dielectric_rigidity: "56",
        Water_content: "14",
        Health_index: "38.3",
      },
      {
        SL: "177",
        Time: "2:40 PM",
        Hydrogen: "12",
        Oxygen: "4350",
        Nitrogen: "65500",
        Methane: "11",
        CO: "870",
        CO2: "11100",
        Ethylene: "16",
        Ethane: "8",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.5",
        Interfacial_V: "41",
        Dielectric_rigidity: "56",
        Water_content: "10",
        Health_index: "38.3",
      },
      {
        SL: "152",
        Time: "12:35 PM",
        Hydrogen: "3",
        Oxygen: "21700",
        Nitrogen: "43200",
        Methane: "0",
        CO: "129",
        CO2: "1530",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "1",
        Power_Factor: "1.59",
        Interfacial_V: "35",
        Dielectric_rigidity: "54",
        Water_content: "21",
        Health_index: "38.3",
      },
      {
        SL: "153",
        Time: "12:40 PM",
        Hydrogen: "3",
        Oxygen: "19500",
        Nitrogen: "42800",
        Methane: "0",
        CO: "209",
        CO2: "2650",
        Ethylene: "30",
        Ethane: "0",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.78",
        Interfacial_V: "40",
        Dielectric_rigidity: "43",
        Water_content: "23",
        Health_index: "38.3",
      },
      {
        SL: "178",
        Time: "2:45 PM",
        Hydrogen: "178",
        Oxygen: "4070",
        Nitrogen: "27300",
        Methane: "144",
        CO: "672",
        CO2: "2260",
        Ethylene: "3",
        Ethane: "10",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "41",
        Dielectric_rigidity: "58",
        Water_content: "12",
        Health_index: "38.1",
      },
      {
        SL: "179",
        Time: "2:50 PM",
        Hydrogen: "10",
        Oxygen: "11900",
        Nitrogen: "55100",
        Methane: "2",
        CO: "403",
        CO2: "1140",
        Ethylene: "6",
        Ethane: "0",
        Acethylene: "2",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "41",
        Dielectric_rigidity: "30",
        Water_content: "23",
        Health_index: "38",
      },
      {
        SL: "180",
        Time: "2:55 PM",
        Hydrogen: "4",
        Oxygen: "5040",
        Nitrogen: "37600",
        Methane: "4",
        CO: "597",
        CO2: "1440",
        Ethylene: "4",
        Ethane: "3",
        Acethylene: "2",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "41",
        Dielectric_rigidity: "56",
        Water_content: "27",
        Health_index: "38",
      },
      {
        SL: "181",
        Time: "3:00 PM",
        Hydrogen: "0",
        Oxygen: "14908",
        Nitrogen: "42800",
        Methane: "0",
        CO: "52",
        CO2: "620",
        Ethylene: "0",
        Ethane: "0",
        Acethylene: "2",
        DBDS: "0",
        Power_Factor: "0.78",
        Interfacial_V: "39",
        Dielectric_rigidity: "60",
        Water_content: "7",
        Health_index: "38",
      },
      {
        SL: "182",
        Time: "3:05 PM",
        Hydrogen: "9",
        Oxygen: "578",
        Nitrogen: "29200",
        Methane: "35",
        CO: "267",
        CO2: "1610",
        Ethylene: "52",
        Ethane: "17",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "0.53",
        Interfacial_V: "42",
        Dielectric_rigidity: "50",
        Water_content: "4",
        Health_index: "36.6",
      },
      {
        SL: "183",
        Time: "3:10 PM",
        Hydrogen: "17",
        Oxygen: "3960",
        Nitrogen: "36100",
        Methane: "29",
        CO: "113",
        CO2: "4420",
        Ethylene: "3",
        Ethane: "5",
        Acethylene: "0",
        DBDS: "5",
        Power_Factor: "0.15",
        Interfacial_V: "45",
        Dielectric_rigidity: "54",
        Water_content: "2",
        Health_index: "36.4",
      },
      {
        SL: "184",
        Time: "3:15 PM",
        Hydrogen: "14",
        Oxygen: "2380",
        Nitrogen: "67400",
        Methane: "78",
        CO: "372",
        CO2: "1850",
        Ethylene: "33",
        Ethane: "1850",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "5.56",
        Interfacial_V: "36",
        Dielectric_rigidity: "43",
        Water_content: "27",
        Health_index: "33.6",
      },
      {
        SL: "185",
        Time: "3:20 PM",
        Hydrogen: "478",
        Oxygen: "9460",
        Nitrogen: "64700",
        Methane: "21",
        CO: "54",
        CO2: "323",
        Ethylene: "0",
        Ethane: "4",
        Acethylene: "0",
        DBDS: "0",
        Power_Factor: "1",
        Interfacial_V: "36",
        Dielectric_rigidity: "43",
        Water_content: "27",
        Health_index: "31",
      },
      
    ],
  };
  console.log(data);

  return (
    <MDBDataTable
      className="table"
      noBottomColumns={true}
      bordered
      small
      data={data}
    ></MDBDataTable>
  );
};

export default About1;
